/* Naruszenie ograniczenia NOT NULL */

ALTER TABLE WYPLATA
MODIFY DATA_WYPLATY DATE NOT NULL;

INSERT INTO WYPLATA (ID_WYPLATY, DATA_WYPLATY, KWOTA_WYPLATY, DEBET, ID_KONTA, ID_PRACOWNIKA)
VALUES (11, NULL, 500, 0, 10, 3);

/*Naruszenie ograniczenia klucza glownego*/
INSERT INTO WYPLATA (ID_WYPLATY, DATA_WYPLATY, KWOTA_WYPLATY, DEBET, ID_KONTA, ID_PRACOWNIKA)
VALUES (9, TO_DATE('23.10.2016', 'DD.MM.YYYY'), 1, 0, 10, 2);

/*Naruszenie ograniczenia unique*/

ALTER TABLE KLIENT
MODIFY IMIE VARCHAR(20)
CONSTRAINT MY_UNIQUE UNIQUE;

INSERT INTO KLIENT (ID_KLIENTA, IMIE, NAZWISKO, DATA_URODZENIA, NR_TELEFONU, EMAIL, ID_ADRESU)
VALUES (11, 'Adam', 'Kot', TO_DATE('12.01.1996', 'DD.MM.YYYY'), 000001111, 'wieszczu@gmail.com', 13);

/*Naruszenie ograniczenia CHECK */
 ALTER TABLE KONTO
    MODIFY( STAN_KONTA NUMBER (10) CONSTRAINT STAN_CHECK
    CHECK (STAN_KONTA >1000 AND STAN_KONTA < 100000)
);
    
INSERT INTO KONTO (ID_KONTA, STAN_KONTA, TYP_KONTA, ID_KLIENTA)
VALUES (11, 500,'Oszczednosciowe', 1);

/*Naruszenie ograniczenia klucza obcego*/
INSERT INTO KONTO (ID_KONTA, STAN_KONTA, TYP_KONTA, ID_KLIENTA)
VALUES (12, 1500,'Oszczednosciowe', 111);
