  ALTER TABLE WYPLATA 
  ADD (MAKS_WYPLATA NUMBER (6)
  CONSTRAINT WYPLATA_MAKS_WYPLATA_NN NOT NULL);
  
  ALTER TABLE PRACOWNICY
  ADD (PODWYZKA NUMBER (4)
  CONSTRAINT PRACOWNICY_PODWYZKA_NN NOT NULL);
  
  ALTER TABLE KLIENT 
  ADD (DRUGIE_IMIE VARCHAR (20)
  CONSTRAINT KLIENT_DRUGIE_IMIE_NN NOT NULL);
  
  ALTER TABLE FILIA
  ADD (WOJEWODZTWO VARCHAR (20)
  CONSTRAINT FILIA_WOJEWODZTWO_NN NOT NULL);
  
  ALTER TABLE KREDYT
  ADD (WALUTA VARCHAR (20)
  CONSTRAINT KREDYT_WALUTA_NN NOT NULL);
  
  ALTER TABLE RATA
  ADD (WYSOKOSC_RATY NUMBER (6)
  CONSTRAINT RATA_WYSOKOSC_RATY_NN NOT NULL);
  
  ALTER TABLE RATA
  MODIFY (KWOTA_WPLATY NUMBER (15)
  CONSTRAINT RATA_KWOTA_WPLATY_NN NOT NULL);
  
  ALTER TABLE WPLATA
  MODIFY (KWOTA_WPLATY NUMBER (15)
  CONSTRAINT WPLATA_KWOTA_WPLATY_NN NOT NULL);
  
  ALTER TABLE WYPLATA
  MODIFY (KWOTA_WYPLATY NUMBER (15)
  CONSTRAINT WPLATA_KWOTA_WYPLATY_NN NOT NULL);
  
  ALTER TABLE ADRESY
  MODIFY (WOJEWODZTWO VARCHAR (30)
  CONSTRAINT ADRESY_WOJEWODZTWO_NN NOT NULL);
  
  ALTER TABLE FILIA DROP (WOJEWODZTWO);
 
  
  ALTER TABLE KLIENT
  ADD UNIQUE (NR_TELEFONU);
  
  
  
  
  