CREATE TABLE ADRESY
  (
    ID_ADRESU     NUMBER (6) CONSTRAINT ADRESY_PK PRIMARY KEY,
    ULICA         VARCHAR (20),
    NR_DOMU       NUMBER    (4),
    NR_MIESZKANIA NUMBER    (4),
    KOD_POCZTOWY  VARCHAR  (6),
    MIEJSCOWOSC   VARCHAR (20),
    WOJEWODZTWO   VARCHAR (20)
  ) ;

CREATE TABLE FILIA
  (
    ID_FILIA NUMBER (6) CONSTRAINT FILIA_PK PRIMARY KEY,
    NAZWA    VARCHAR (20) ,
    ID_ADRESU NUMBER (6),
    CONSTRAINT FILIA_FK FOREIGN KEY (ID_ADRESU) REFERENCES ADRESY(ID_ADRESU)
  ) ;

CREATE TABLE STANOWISKO
  (
    ID_STANOWISKA      NUMBER (6) CONSTRAINT STANOWISKO_PK PRIMARY KEY ,
    NAZWA              VARCHAR (20) 
  
  ) ;

CREATE TABLE DZIAL
  (
    ID_DZIAL       NUMBER (6) CONSTRAINT DZIAL_PK PRIMARY KEY,
    NAZWA          VARCHAR (20),
    ID_FILIA       NUMBER (6),
   CONSTRAINT DZIAL_FK FOREIGN KEY (ID_FILIA) REFERENCES FILIA(ID_FILIA)
  ) ;


CREATE TABLE KLIENT
  (
    ID_KLIENTA       NUMBER(6) CONSTRAINT KLIENT_PK PRIMARY KEY ,
    IMIE             VARCHAR (20) ,
    NAZWISKO         VARCHAR (20) ,
    DATA_URODZENIA   DATE ,
    NR_TELEFONU      NUMBER (9) ,
    EMAIL            VARCHAR (30) ,
    ID_ADRESU        NUMBER (6),
    CONSTRAINT KLIENT_FK FOREIGN KEY (ID_ADRESU) REFERENCES ADRESY(ID_ADRESU)
  ) ;


CREATE TABLE KONTO
  (
    ID_KONTA          NUMBER (6) CONSTRAINT KONTO_PK PRIMARY KEY ,
    STAN_KONTA        NUMBER (10) ,
    TYP_KONTA         VARCHAR (20) ,
    ID_KLIENTA        NUMBER (6),
   CONSTRAINT KONTO_FK FOREIGN KEY (ID_KLIENTA) REFERENCES KLIENT (ID_KLIENTA)
  ) ;

CREATE TABLE PRACOWNICY
  (
    ID_PRACOWNIKA            NUMBER (6) CONSTRAINT PRACOWNICY_PK PRIMARY KEY,
    IMIE                     VARCHAR (20) ,
    NAZWISKO                 VARCHAR (20) ,
    NR_TELEFONU              NUMBER (9),
    EMAIL                    VARCHAR (30) ,
    DATA_ZATRUDNIENIA        DATE ,
    WYNAGRODZENIE_PODSTAWOWE NUMBER (10) ,
    WYNAGRODZENIE_DODATKOWE  NUMBER (10),
    ID_ADRESU                NUMBER (6),
    CONSTRAINT PRACOWNICY_FK FOREIGN KEY (ID_ADRESU) REFERENCES ADRESY (ID_ADRESU),
    ID_STANOWISKA            NUMBER (6),
    CONSTRAINT PRACOWNICY_FK1 FOREIGN KEY (ID_STANOWISKA) REFERENCES STANOWISKO(ID_STANOWISKA),
    ID_DZIAL                 NUMBER (6) ,
    CONSTRAINT PRACOWNICY_FK2 FOREIGN KEY (ID_DZIAL) REFERENCES DZIAL(ID_DZIAL)
  ) ;

CREATE TABLE KREDYT
  (
    ID_KREDYTU               NUMBER (6) CONSTRAINT KREDYT_PK PRIMARY KEY,
    KWOTA                    NUMBER (10),
    DATA_ZACIAGNIECIA        DATE ,
    ID_KONTA                 NUMBER (6) ,
    CONSTRAINT KREDYT_FK FOREIGN KEY (ID_KONTA) REFERENCES KONTO(ID_KONTA),
    ID_PRACOWNIKA            NUMBER (6) ,
    CONSTRAINT KREDYT_FK1 FOREIGN KEY (ID_PRACOWNIKA) REFERENCES PRACOWNICY(ID_PRACOWNIKA)

  ) ;





CREATE TABLE RATA
  (
    ID_RATY           NUMBER (6) CONSTRAINT RATA_PK PRIMARY KEY ,
    NR_RATY           NUMBER (10),
    DATA_WPLATY       DATE ,
    KWOTA_WPLATY      NUMBER (10),
    ID_KREDYTU        NUMBER (6) ,
    CONSTRAINT RATA_FK FOREIGN KEY (ID_KREDYTU) REFERENCES KREDYT (ID_KREDYTU)
  ) ;



CREATE TABLE WPLATA
  (
    ID_WPLATY                NUMBER (6) CONSTRAINT WPLATA_PK PRIMARY KEY,
    DATA_WPLATY              DATE ,
    KWOTA_WPLATY             NUMBER (10),
    ID_KONTA                 NUMBER (6),
    CONSTRAINT WPLATA_FK FOREIGN KEY (ID_KONTA) REFERENCES KONTO (ID_KONTA),
    ID_PRACOWNIKA            NUMBER (6) ,
    CONSTRAINT WPLATA_FK1 FOREIGN KEY (ID_PRACOWNIKA) REFERENCES PRACOWNICY (ID_PRACOWNIKA)
  ) ;


CREATE TABLE WYPLATA
  (
    ID_WYPLATY               NUMBER (6) CONSTRAINT WYPLATA_PK PRIMARY KEY,
    DATA_WYPLATY             DATE ,
    KWOTA_WYPLATY            NUMBER (10),
    DEBET                    NUMBER (6),
    ID_KONTA                 NUMBER (6),
    CONSTRAINT WYPLATA_FK FOREIGN KEY (ID_KONTA) REFERENCES KONTO (ID_KONTA),
    ID_PRACOWNIKA            NUMBER (6),
    CONSTRAINT WYPLATA_FK1 FOREIGN KEY (ID_PRACOWNIKA) REFERENCES PRACOWNICY (ID_PRACOWNIKA)
    
  ) ;