CREATE SEQUENCE adresy_seq;
CREATE SEQUENCE filia_seq;
CREATE SEQUENCE stanowisko_seq;
CREATE SEQUENCE dzial_seq;
CREATE SEQUENCE klient_seq;
CREATE SEQUENCE konto_seq;
CREATE SEQUENCE pracownicy_seq;
CREATE SEQUENCE kredyt_seq;
CREATE SEQUENCE rata_seq;
CREATE SEQUENCE wplata_seq;
CREATE SEQUENCE wyplata_seq;

INSERT INTO Adresy (ID_ADRESU, Ulica, Nr_Domu, Nr_Mieszkania, Kod_Pocztowy, Miejscowosc, Wojewodztwo)
VALUES (ADRESY_SEQ.NEXTVAL, 'Mala', 1, 2, '11-111', 'Warszawa', 'Mazowieckie');

INSERT INTO FILIA (ID_FILIA, NAZWA, ID_ADRESU)
VALUES (filia_seq.nextval, 'WWaMal1', 1);

INSERT INTO STANOWISKO (ID_STANOWISKA, NAZWA)
VALUES (STANOWISKO_SEQ.NEXTVAL, 'Dyrektor');

INSERT INTO DZIAL (ID_DZIAL, NAZWA, ID_FILIA)
VALUES (DZIAL_SEQ.NEXTVAL, 'Finansowy', 1);

INSERT INTO KLIENT (ID_KLIENTA, IMIE, NAZWISKO, DATA_URODZENIA, NR_TELEFONU, EMAIL, ID_ADRESU)
VALUES (KLIENT_SEQ.NEXTVAL, 'Tomasz', 'Kowalski', TO_DATE('01.01.2001', 'DD.MM.YYYY'), 011011011, 'niskikot@spoko.pl', 1);

INSERT INTO KONTO (ID_KONTA, STAN_KONTA, TYP_KONTA, ID_KLIENTA)
VALUES (KONTO_SEQ.NEXTVAL, 1500,'Oszczednosciowe', 1);

INSERT INTO PRACOWNICY (ID_PRACOWNIKA, IMIE, NAZWISKO, NR_TELEFONU, EMAIL, DATA_ZATRUDNIENIA, WYNAGRODZENIE_PODSTAWOWE, WYNAGRODZENIE_DODATKOWE, ID_ADRESU, ID_STANOWISKA, ID_DZIAL)
VALUES (PRACOWNICY_SEQ.NEXTVAL, 'Piotr', 'Sienkiewicz', 011011011,'niskikot@spoko.pl', TO_DATE('01.01.2005', 'DD.MM.YYYY'), 5000, 1000, 1, 1, 1);

INSERT INTO KREDYT (ID_KREDYTU, KWOTA, DATA_ZACIAGNIECIA, ID_KONTA, ID_PRACOWNIKA)
VALUES (KREDYT_SEQ.NEXTVAL, 1000, TO_DATE('01.01.2005', 'DD.MM.YYYY'), 1, 1);

INSERT INTO RATA (ID_RATY, NR_RATY, DATA_WPLATY, KWOTA_WPLATY, ID_KREDYTU)
VALUES (RATA_SEQ.NEXTVAL, 1, TO_DATE('01.01.2005', 'DD.MM.YYYY'), 200, 1);

INSERT INTO WPLATA (ID_WPLATY, DATA_WPLATY, KWOTA_WPLATY, ID_KONTA, ID_PRACOWNIKA)
VALUES (RATA_SEQ.NEXTVAL, TO_DATE('01.01.2005', 'DD.MM.YYYY'), 500, 1, 1);

INSERT INTO WYPLATA (ID_WYPLATY, DATA_WYPLATY, KWOTA_WYPLATY, DEBET, ID_KONTA, ID_PRACOWNIKA)
VALUES (WYPLATA_SEQ.NEXTVAL, TO_DATE('01.01.2005', 'DD.MM.YYYY'), 500, 0, 1, 1);

