/*1. Stworzyć widok zawierający następujące informacje o ostatniej wyplacie: 
data wyplaty, imię nazwisko klienta, nr konta, kwota wyplaty */

CREATE OR REPLACE VIEW zadanie1 AS
SELECT WYPLATA.DATA_WYPLATY, KLIENT.IMIE, KLIENT.NAZWISKO, KONTO.ID_KONTA NR_KONTA, WYPLATA.KWOTA_WYPLATY 
FROM WYPLATA
JOIN (
SELECT ID_KONTA, MAX (DATA_WYPLATY) as MaxDate
FROM WYPLATA
GROUP BY ID_KONTA) tmp ON WYPLATA.ID_KONTA = tmp.ID_KONTA AND WYPLATA.DATA_WYPLATY = tmp.MaxDate
JOIN KONTO ON KONTO.ID_KONTA = WYPLATA.ID_KONTA
JOIN KLIENT ON KLIENT.ID_KLIENTA = KONTO.ID_KLIENTA
ORDER BY KONTO.ID_KONTA;

SELECT *FROM zadanie1;

/*2. Stworzyć widok zawierający informacje o klientach posiadajacych stan konta powyżej średniej */

CREATE OR REPLACE VIEW zadanie2 AS
    SELECT KONTO.ID_KONTA NR_KONTA, KONTO.STAN_KONTA, KLIENT.IMIE, KLIENT.NAZWISKO 
    FROM KONTO
    JOIN (
    SELECT ID_KONTA
    FROM KONTO
    WHERE STAN_KONTA > (SELECT AVG(STAN_KONTA) FROM KONTO)
    GROUP BY ID_KONTA
    ORDER BY ID_KONTA
    ) TMP ON TMP.ID_KONTA = KONTO.ID_KONTA
    JOIN KLIENT ON KLIENT.ID_KLIENTA = KONTO.ID_KLIENTA;
   
   SELECT *FROM zadanie2; 
   
/*3. Stworzyć widok zawierający informacje o tym ile osób pracuje w poszczególnym dziale.*/

CREATE OR REPLACE VIEW zadanie3 AS
SELECT NAZWA, COUNT(PRACOWNICY.ID_PRACOWNIKA) LICZBA_OSOB
FROM DZIAL
JOIN PRACOWNICY ON DZIAL.ID_DZIAL = PRACOWNICY.ID_DZIAL
GROUP BY DZIAL.NAZWA
ORDER BY DZIAL.NAZWA;

SELECT *FROM zadanie3;

/*4. Wyswietl miesieczne zestawienie zawierajace nastepujace informacje: rok, miesiac, liczbe oraz sume wplat, ktore odbyly sie w tym miesiacu.*/

SELECT EXTRACT (MONTH FROM DATA_WPLATY) MIESIAC, EXTRACT(YEAR FROM DATA_WPLATY) ROK, COUNT(ID_WPLATY) AS LICZBA_WPLAT, SUM (KWOTA_WPLATY) AS SUMA_WPLAT
FROM WPLATA
GROUP BY EXTRACT (MONTH FROM DATA_WPLATY), EXTRACT (YEAR FROM DATA_WPLATY)
ORDER BY EXTRACT (MONTH FROM DATA_WPLATY), EXTRACT (YEAR FROM DATA_WPLATY);


/*5. Wyswietl osoby pracujace na stanowisku sprzataczka. */
SELECT STANOWISKO.NAZWA STANOWISKO, PRACOWNICY.IMIE, PRACOWNICY.NAZWISKO
FROM PRACOWNICY
JOIN STANOWISKO ON PRACOWNICY.ID_STANOWISKA = STANOWISKO.ID_STANOWISKA
WHERE STANOWISKO.NAZWA = 'Sprzataczka';


/* 6. Stworzyć widok przedstawiający: imię i nazwisko pracownika wraz ze stanowiskiem, którzy mają ponad 2200 wynagrodzenia (podstawowego i dodatkowego) */ 
CREATE OR REPLACE VIEW zadanie6  AS
SELECT DISTINCT PRACOWNICY.IMIE, PRACOWNICY.NAZWISKO,  PRACOWNICY.WYNAGRODZENIE_PODSTAWOWE, PRACOWNICY.WYNAGRODZENIE_DODATKOWE, STANOWISKO.NAZWA STANOWISKO
FROM PRACOWNICY 
JOIN STANOWISKO ON PRACOWNICY.ID_STANOWISKA = STANOWISKO.ID_STANOWISKA
GROUP BY PRACOWNICY.IMIE, PRACOWNICY.NAZWISKO, PRACOWNICY.WYNAGRODZENIE_PODSTAWOWE, PRACOWNICY.WYNAGRODZENIE_DODATKOWE, STANOWISKO.NAZWA
having (PRACOWNICY.WYNAGRODZENIE_PODSTAWOWE+PRACOWNICY.WYNAGRODZENIE_DODATKOWE)>2200;

SELECT *FROM zadanie6; 

/* 7. Stworzyć widok przedstawiający imię, nazwisko oraz adres zamieszkania zarówno pracowników, jak i klientów banku. */
CREATE OR REPLACE VIEW zadanie7  AS
SELECT  IMIE, NAZWISKO, ADRESY.ULICA, ADRESY.NR_DOMU, ADRESY.NR_MIESZKANIA, ADRESY.KOD_POCZTOWY, ADRESY.MIEJSCOWOSC 
FROM PRACOWNICY 
JOIN ADRESY ON ADRESY.ID_ADRESU = PRACOWNICY.ID_ADRESU
UNION
SELECT IMIE,NAZWISKO, ADRESY.ULICA, ADRESY.NR_DOMU, ADRESY.NR_MIESZKANIA, ADRESY.KOD_POCZTOWY, ADRESY.MIEJSCOWOSC 
FROM KLIENT
JOIN ADRESY ON ADRESY.ID_ADRESU = KLIENT.ID_ADRESU;

SELECT *FROM zadanie7;

/* 8. Wyswietlic adresy, pod którymi zameldowani są równocześnie klient i pracownik banku*/
CREATE OR REPLACE VIEW zadanie8  AS
SELECT  ADRESY.ULICA, ADRESY.NR_DOMU, ADRESY.NR_MIESZKANIA, ADRESY.KOD_POCZTOWY, ADRESY.MIEJSCOWOSC 
FROM PRACOWNICY 
JOIN ADRESY ON ADRESY.ID_ADRESU = PRACOWNICY.ID_ADRESU
INTERSECT
SELECT ADRESY.ULICA, ADRESY.NR_DOMU, ADRESY.NR_MIESZKANIA, ADRESY.KOD_POCZTOWY, ADRESY.MIEJSCOWOSC 
FROM KLIENT
JOIN ADRESY ON ADRESY.ID_ADRESU = KLIENT.ID_ADRESU;

SELECT *FROM zadanie8;

/*9. Znajdz klientow, ktorzy wzieli kredyt*/

SELECT IMIE, NAZWISKO, KREDYT.KWOTA KWOTA_KREDYTU
FROM KLIENT
JOIN KONTO ON KONTO.ID_KLIENTA = KLIENT.ID_KLIENTA
JOIN KREDYT ON KREDYT.ID_KONTA = KONTO.ID_KONTA
WHERE EXISTS (SELECT 'x' FROM KREDYT);


/*10. Wyświetl następujące informację o pracownikach: 
imię, nazwisko oraz czy ich wynagrodzenie dodatkowe jest “NIZSZE”, “WYZSZE” czy “ROWNE” 500 (zł).*/

SELECT IMIE, NAZWISKO, WYNAGRODZENIE_DODATKOWE, 
CASE WHEN WYNAGRODZENIE_DODATKOWE<500 THEN 'NIZSZE' 
WHEN WYNAGRODZENIE_DODATKOWE>500 THEN 'WYZSZE' 
WHEN WYNAGRODZENIE_DODATKOWE=500 THEN 'ROWNE' 
END as WYNIK FROM PRACOWNICY;


